<a href="https://colab.research.google.com/github/nimitraheja/nimitraheja/blob/main/knn_imputer_(multivariate).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
df = pd.read_csv('/content/train.csv')[['Age','Pclass','Fare','Survived']]
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [2]:
X = df.drop(columns=['Survived'])
y = df['Survived']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)
X_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [7]:
knn = KNNImputer(n_neighbors=5,weights='uniform')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [8]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7039106145251397